[app]
port = 1344
log_level="debug"
write_logs_to_console= false
services= ["echo"]
debugging_headers=true
web_server_host = "127.0.0.1:8081" #Example: "localhost:8081" , replace localhost with the ICAP server IP address.
web_server_endpoint = "/service/message"  

[echo]
vendor = "echo"
service_caption= "echo service"   #Service
service_tag = "ECHO ICAP"  #ISTAG
req_mode=true
resp_mode=true
shadow_service=false
preview_bytes = "1024" #byte
preview_enabled = false # options send preview header or not
process_extensions = ["pdf", "zip", "com"] # * = everything except the ones in bypass, unknown = system couldn't find out the type of the file
reject_extensions = ["docx"]
bypass_extensions = ["*"]
#max file size value from 1 to 9223372036854775807, and value of zero means unlimited
max_filesize = 0 #bytes
return_original_if_max_file_size_exceeded=false
return_400_if_file_ext_rejected=false
